In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
dataset = pd.read_csv("/content/drive/My Drive/Alarm1.xlsx - Sheet1.csv")

In [4]:
bankdata=dataset[["Tank Level","S1 Input PT","S1 Output PT","S1 Output Flow","Temperature","Class"]]

In [5]:
X = bankdata.drop('Class', axis=1)
y = bankdata['Class']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [7]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [8]:
y_pred = svclassifier.predict(X_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[23  0  0  3]
 [ 0 27  0 12]
 [ 0  0 19  4]
 [ 0  6  3 74]]
              precision    recall  f1-score   support

           A       1.00      0.88      0.94        26
           C       0.82      0.69      0.75        39
           I       0.86      0.83      0.84        23
           Z       0.80      0.89      0.84        83

    accuracy                           0.84       171
   macro avg       0.87      0.82      0.84       171
weighted avg       0.84      0.84      0.84       171

